import pluralize from 'pluralize';
import { describe, expect, it } from 'vitest';
import type { Pluralize, Singularize } from '../src/util/type-naming.ts';

// `Singularize` and `Pluralize` transcribe `pluralize`'s rule set into the type system so the
// generated `entities` can be keyed by the names a `typeNameMapper: 'singularize'` build
// publishes. A transcription can drift from what it transcribes, in either direction: the
// types could be wrong today, or a future `pluralize` could change a rule out from under
// them. This table is what closes both gaps.
//
// Each row is a word with the singular and plural `pluralize` gives it. The `it` below checks
// the row against the real `pluralize` at run time, and the `Verified` alias underneath
// checks the same row against the types at compile time (`npm run typecheck` — vitest does
// not run type assertions). So a row can only stay green while the types and the library
// agree, and neither side can be edited to fit the other on its own.
//
// A word the types decline to decide resolves to `string`, which is allowed here: it widens
// that table's entity keys to an index signature rather than naming a field the build never
// publishes. Being loose only costs autocomplete, so it passes; being *wrong* would put a
// type error on correct code, so it fails.
const WORDS = [
  ['abTests', 'abTest', 'abTests'],
  ['abilities', 'ability', 'abilities'],
  ['abuses', 'abuse', 'abuses'],
  ['accessTokens', 'accessToken', 'accessTokens'],
  ['account', 'account', 'accounts'],
  ['accounts', 'account', 'accounts'],
  ['activities', 'activity', 'activities'],
  ['address', 'address', 'addresses'],
  ['addresses', 'address', 'addresses'],
  ['affix', 'affix', 'affixes'],
  ['agenda', 'agenda', 'agenda'],
  ['aliases', 'alias', 'aliases'],
  ['alumnus', 'alumnus', 'alumni'],
  ['analyses', 'analysis', 'analyses'],
  ['analysis', 'analysis', 'analyses'],
  ['analyticsEvents', 'analyticsEvent', 'analyticsEvents'],
  ['antennas', 'antenna', 'antennas'],
  ['apex', 'apex', 'apexes'],
  ['apiKey', 'apiKey', 'apiKeys'],
  ['apiKeys', 'apiKey', 'apiKeys'],
  ['apices', 'apice', 'apices'],
  ['appendixes', 'appendix', 'appendixes'],
  ['archives', 'archive', 'archives'],
  ['areas', 'area', 'areas'],
  ['articles', 'article', 'articles'],
  ['atlases', 'atlas', 'atlases'],
  ['attachments', 'attachment', 'attachments'],
  ['attorney', 'attorney', 'attorneys'],
  ['auditLog', 'auditLog', 'auditLogs'],
  ['auditLogs', 'auditLog', 'auditLogs'],
  ['automaton', 'automaton', 'automata'],
  ['avalanches', 'avalanch', 'avalanches'],
  ['avatars', 'avatar', 'avatars'],
  ['axe', 'axe', 'axes'],
  ['axis', 'axi', 'axes'],
  ['bases', 'base', 'bases'],
  ['basis', 'basi', 'bases'],
  ['batches', 'batch', 'batches'],
  ['beacon', 'beacon', 'beacons'],
  ['beans', 'bean', 'beans'],
  ['belief', 'belief', 'beliefs'],
  ['believes', 'believe', 'believes'],
  ['biases', 'biase', 'biases'],
  ['birdies', 'birdy', 'birdies'],
  ['blogPosts', 'blogPost', 'blogPosts'],
  ['bodies', 'body', 'bodies'],
  ['body', 'body', 'bodies'],
  ['bonus', 'bonus', 'bonuses'],
  ['bonuses', 'bonus', 'bonuses'],
  ['bookies', 'booky', 'bookies'],
  ['bookshelves', 'bookshelf', 'bookshelves'],
  ['box', 'box', 'boxes'],
  ['boxes', 'box', 'boxes'],
  ['branch', 'branch', 'branches'],
  ['branches', 'branch', 'branches'],
  ['brief', 'brief', 'briefs'],
  ['brownies', 'browny', 'brownies'],
  ['brushes', 'brush', 'brushes'],
  ['bus', 'bus', 'buses'],
  ['buses', 'bus', 'buses'],
  ['bushes', 'bush', 'bushes'],
  ['buzzes', 'buzz', 'buzzes'],
  ['caches', 'cach', 'caches'],
  ['caddies', 'caddy', 'caddies'],
  ['calf', 'calf', 'calves'],
  ['calves', 'calf', 'calves'],
  ['campus', 'campus', 'campuses'],
  ['campuses', 'campus', 'campuses'],
  ['canvases', 'canvase', 'canvases'],
  ['carve', 'carve', 'carves'],
  ['carves', 'carve', 'carves'],
  ['cases', 'case', 'cases'],
  ['categories', 'category', 'categories'],
  ['category', 'category', 'categories'],
  ['causes', 'cause', 'causes'],
  ['cave', 'cave', 'caves'],
  ['caves', 'cave', 'caves'],
  ['census', 'census', 'censuses'],
  ['censuses', 'census', 'censuses'],
  ['cervices', 'cervice', 'cervices'],
  ['chairman', 'chairman', 'chairmen'],
  ['channels', 'channel', 'channels'],
  ['chef', 'chef', 'chefs'],
  ['chief', 'chief', 'chiefs'],
  ['child', 'child', 'children'],
  ['children', 'child', 'children'],
  ['chimney', 'chimney', 'chimneys'],
  ['chinese', 'chinese', 'chinese'],
  ['choices', 'choice', 'choices'],
  ['cities', 'city', 'cities'],
  ['citizen', 'citizen', 'citizens'],
  ['citizens', 'citizen', 'citizens'],
  ['city', 'city', 'cities'],
  ['class', 'class', 'classes'],
  ['classes', 'class', 'classes'],
  ['clauses', 'clause', 'clauses'],
  ['codex', 'codex', 'codices'],
  ['codices', 'codex', 'codices'],
  ['collies', 'collie', 'collies'],
  ['comment', 'comment', 'comments'],
  ['comments', 'comment', 'comments'],
  ['companies', 'company', 'companies'],
  ['company', 'company', 'companies'],
  ['complex', 'complex', 'complexes'],
  ['cookies', 'cooky', 'cookies'],
  ['countries', 'country', 'countries'],
  ['country', 'country', 'countries'],
  ['coupon', 'coupon', 'coupons'],
  ['courses', 'course', 'courses'],
  ['crashes', 'crash', 'crashes'],
  ['crises', 'crisis', 'crises'],
  ['crisis', 'crisis', 'crises'],
  ['criteria', 'criterion', 'criteria'],
  ['criterion', 'criterion', 'criteria'],
  ['currencies', 'currency', 'currencies'],
  ['curses', 'curse', 'curses'],
  ['curves', 'curve', 'curves'],
  ['customer', 'customer', 'customers'],
  ['customers', 'customer', 'customers'],
  ['cuties', 'cutie', 'cuties'],
  ['data', 'datum', 'data'],
  ['databases', 'database', 'databases'],
  ['datum', 'datum', 'data'],
  ['day', 'day', 'days'],
  ['days', 'day', 'days'],
  ['deer', 'deer', 'deer'],
  ['deliveries', 'delivery', 'deliveries'],
  ['delves', 'delf', 'delves'],
  ['devices', 'device', 'devices'],
  ['diagnoses', 'diagnosis', 'diagnoses'],
  ['diagnosis', 'diagnosis', 'diagnoses'],
  ['dilemmas', 'dilemma', 'dilemmas'],
  ['dingo', 'dingo', 'dingoes'],
  ['dingoes', 'dingo', 'dingoes'],
  ['directories', 'directory', 'directories'],
  ['discoveries', 'discovery', 'discoveries'],
  ['dish', 'dish', 'dishes'],
  ['dishes', 'dish', 'dishes'],
  ['displays', 'display', 'displays'],
  ['documents', 'document', 'documents'],
  ['dogma', 'dogma', 'dogmata'],
  ['donkey', 'donkey', 'donkeys'],
  ['doses', 'dose', 'doses'],
  ['doves', 'dove', 'doves'],
  ['drives', 'drive', 'drives'],
  ['duplex', 'duplex', 'duplexes'],
  ['duties', 'duty', 'duties'],
  ['duty', 'duty', 'duties'],
  ['dwarf', 'dwarf', 'dwarves'],
  ['dwarves', 'dwarf', 'dwarves'],
  ['eave', 'eave', 'eaves'],
  ['echo', 'echo', 'echoes'],
  ['echoes', 'echo', 'echoes'],
  ['elf', 'elf', 'elves'],
  ['elves', 'elf', 'elves'],
  ['emailTemplates', 'emailTemplate', 'emailTemplates'],
  ['emphases', 'emphasis', 'emphases'],
  ['emphasis', 'emphasis', 'emphases'],
  ['entities', 'entity', 'entities'],
  ['entity', 'entity', 'entities'],
  ['entries', 'entry', 'entries'],
  ['equipment', 'equipment', 'equipment'],
  ['essays', 'essay', 'essays'],
  ['events', 'event', 'events'],
  ['excuses', 'excus', 'excuses'],
  ['factories', 'factory', 'factories'],
  ['families', 'family', 'families'],
  ['family', 'family', 'families'],
  ['faxes', 'fax', 'faxes'],
  ['featureFlags', 'featureFlag', 'featureFlags'],
  ['feet', 'foot', 'feet'],
  ['files', 'file', 'files'],
  ['fish', 'fish', 'fish'],
  ['fizzes', 'fizz', 'fizzes'],
  ['flashes', 'flash', 'flashes'],
  ['focus', 'focus', 'foci'],
  ['focuses', 'focus', 'focuses'],
  ['formulas', 'formula', 'formulas'],
  ['garden', 'garden', 'gardens'],
  ['gardens', 'garden', 'gardens'],
  ['gases', 'gas', 'gases'],
  ['gateways', 'gateway', 'gateways'],
  ['geese', 'goose', 'geese'],
  ['genus', 'genus', 'genera'],
  ['glove', 'glove', 'gloves'],
  ['gloves', 'glove', 'gloves'],
  ['goalies', 'goalie', 'goalies'],
  ['goldfish', 'goldfish', 'goldfish'],
  ['grave', 'grave', 'graves'],
  ['graves', 'grave', 'graves'],
  ['groove', 'groove', 'grooves'],
  ['groupies', 'groupie', 'groupies'],
  ['groves', 'grove', 'groves'],
  ['half', 'half', 'halves'],
  ['halves', 'half', 'halves'],
  ['headquarters', 'headquarters', 'headquarters'],
  ['helices', 'helice', 'helices'],
  ['helix', 'helix', 'helixes'],
  ['hero', 'hero', 'heroes'],
  ['heroes', 'hero', 'heroes'],
  ['histories', 'history', 'histories'],
  ['holidays', 'holiday', 'holidays'],
  ['hoodies', 'hoody', 'hoodies'],
  ['hoof', 'hoof', 'hooves'],
  ['hooves', 'hoof', 'hooves'],
  ['horizon', 'horizon', 'horizons'],
  ['horses', 'horse', 'horses'],
  ['house', 'house', 'houses'],
  ['houses', 'house', 'houses'],
  ['housewives', 'housewife', 'housewives'],
  ['human', 'human', 'humans'],
  ['humans', 'human', 'humans'],
  ['hypotheses', 'hypothesis', 'hypotheses'],
  ['icon', 'icon', 'icons'],
  ['ideas', 'idea', 'ideas'],
  ['identities', 'identity', 'identities'],
  ['images', 'image', 'images'],
  ['improves', 'improve', 'improves'],
  ['index', 'index', 'indices'],
  ['indexes', 'index', 'indexes'],
  ['indices', 'index', 'indices'],
  ['information', 'information', 'information'],
  ['inventories', 'inventory', 'inventories'],
  ['invoices', 'invoice', 'invoices'],
  ['irises', 'iris', 'irises'],
  ['jackknives', 'jackknife', 'jackknives'],
  ['japanese', 'japanese', 'japanese'],
  ['journey', 'journey', 'journeys'],
  ['journeys', 'journey', 'journeys'],
  ['key', 'key', 'keys'],
  ['keys', 'key', 'keys'],
  ['kitchens', 'kitchen', 'kitchens'],
  ['knife', 'knife', 'knives'],
  ['knives', 'knife', 'knives'],
  ['lassies', 'lassie', 'lassies'],
  ['launches', 'launch', 'launches'],
  ['leaf', 'leaf', 'leaves'],
  ['leaves', 'leaf', 'leaves'],
  ['lemma', 'lemma', 'lemmata'],
  ['lens', 'len', 'lens'],
  ['lenses', 'lense', 'lenses'],
  ['libraries', 'library', 'libraries'],
  ['licenses', 'license', 'licenses'],
  ['life', 'life', 'lives'],
  ['lineItems', 'lineItem', 'lineItems'],
  ['lives', 'life', 'lives'],
  ['loaf', 'loaf', 'loaves'],
  ['loans', 'loan', 'loans'],
  ['loaves', 'loaf', 'loaves'],
  ['loginAttempts', 'loginAttempt', 'loginAttempts'],
  ['logos', 'logo', 'logos'],
  ['logs', 'log', 'logs'],
  ['man', 'man', 'men'],
  ['match', 'match', 'matches'],
  ['matches', 'match', 'matches'],
  ['matrices', 'matrix', 'matrices'],
  ['matrix', 'matrix', 'matrices'],
  ['means', 'mean', 'means'],
  ['media', 'media', 'media'],
  ['memories', 'memory', 'memories'],
  ['memos', 'memo', 'memos'],
  ['men', 'man', 'men'],
  ['messages', 'message', 'messages'],
  ['metadata', 'metadatum', 'metadata'],
  ['mice', 'mouse', 'mice'],
  ['midwives', 'midwife', 'midwives'],
  ['money', 'money', 'monies'],
  ['monies', 'money', 'monies'],
  ['monkey', 'monkey', 'monkeys'],
  ['moves', 'move', 'moves'],
  ['movies', 'movie', 'movies'],
  ['murex', 'murex', 'murices'],
  ['murices', 'murex', 'murices'],
  ['muses', 'mus', 'muses'],
  ['narcissi', 'narcissi', 'narcissis'],
  ['nerves', 'nerve', 'nerves'],
  ['newbies', 'newby', 'newbies'],
  ['news', 'news', 'news'],
  ['niches', 'nich', 'niches'],
  ['noses', 'nose', 'noses'],
  ['notices', 'notice', 'notices'],
  ['notifications', 'notification', 'notifications'],
  ['nurses', 'nurse', 'nurses'],
  ['oasis', 'oasi', 'oases'],
  ['oauthToken', 'oauthToken', 'oauthTokens'],
  ['ocean', 'ocean', 'oceans'],
  ['oceans', 'ocean', 'oceans'],
  ['octopi', 'octopi', 'octopis'],
  ['octopus', 'octopus', 'octopuses'],
  ['offices', 'office', 'offices'],
  ['oldies', 'oldy', 'oldies'],
  ['olives', 'olive', 'olives'],
  ['order', 'order', 'orders'],
  ['orderItems', 'orderItem', 'orderItems'],
  ['orders', 'order', 'orders'],
  ['organ', 'organ', 'organs'],
  ['organizationMember', 'organizationMember', 'organizationMembers'],
  ['organizations', 'organization', 'organizations'],
  ['organs', 'organ', 'organs'],
  ['oxen', 'ox', 'oxen'],
  ['pageViews', 'pageView', 'pageViews'],
  ['parentheses', 'parenthesis', 'parentheses'],
  ['parties', 'party', 'parties'],
  ['party', 'party', 'parties'],
  ['passerby', 'passerby', 'passersby'],
  ['passwordResets', 'passwordReset', 'passwordResets'],
  ['pauses', 'pause', 'pauses'],
  ['payments', 'payment', 'payments'],
  ['people', 'person', 'people'],
  ['permissions', 'permission', 'permissions'],
  ['person', 'person', 'people'],
  ['phases', 'phase', 'phases'],
  ['phenomenon', 'phenomenon', 'phenomena'],
  ['phoenix', 'phoenix', 'phoenixes'],
  ['photos', 'photo', 'photos'],
  ['pianos', 'piano', 'pianos'],
  ['pickaxe', 'pickaxe', 'pickaxes'],
  ['pies', 'pie', 'pies'],
  ['pitches', 'pitch', 'pitches'],
  ['pizzas', 'pizza', 'pizzas'],
  ['plans', 'plan', 'plans'],
  ['police', 'police', 'police'],
  ['policies', 'policy', 'policies'],
  ['polygon', 'polygon', 'polygons'],
  ['portfolios', 'portfolio', 'portfolios'],
  ['poses', 'pose', 'poses'],
  ['post', 'post', 'posts'],
  ['posts', 'post', 'posts'],
  ['potato', 'potato', 'potatoes'],
  ['potatoes', 'potato', 'potatoes'],
  ['practices', 'practice', 'practices'],
  ['prefix', 'prefix', 'prefixes'],
  ['prefixes', 'prefix', 'prefixes'],
  ['priceHistories', 'priceHistory', 'priceHistories'],
  ['prices', 'price', 'prices'],
  ['priorities', 'priority', 'priorities'],
  ['processes', 'process', 'processes'],
  ['product', 'product', 'products'],
  ['products', 'product', 'products'],
  ['projects', 'project', 'projects'],
  ['proof', 'proof', 'proofs'],
  ['properties', 'property', 'properties'],
  ['proves', 'prove', 'proves'],
  ['proxies', 'proxy', 'proxies'],
  ['proxy', 'proxy', 'proxies'],
  ['purchases', 'purchase', 'purchases'],
  ['pushes', 'push', 'pushes'],
  ['quantities', 'quantity', 'quantities'],
  ['queens', 'queen', 'queens'],
  ['queries', 'query', 'queries'],
  ['quiz', 'quiz', 'quizzes'],
  ['quizzes', 'quiz', 'quizzes'],
  ['radio', 'radio', 'radios'],
  ['radios', 'radio', 'radios'],
  ['radius', 'radius', 'radii'],
  ['ratings', 'rating', 'ratings'],
  ['ratios', 'ratio', 'ratios'],
  ['reactions', 'reaction', 'reactions'],
  ['refreshTokens', 'refreshToken', 'refreshTokens'],
  ['reindeer', 'reindeer', 'reindeer'],
  ['releases', 'release', 'releases'],
  ['removes', 'remove', 'removes'],
  ['repositories', 'repository', 'repositories'],
  ['reserves', 'reserve', 'reserves'],
  ['reviews', 'review', 'reviews'],
  ['roles', 'role', 'roles'],
  ['roof', 'roof', 'roofs'],
  ['rookies', 'rooky', 'rookies'],
  ['roses', 'rose', 'roses'],
  ['salves', 'salf', 'salves'],
  ['scans', 'scan', 'scans'],
  ['scarf', 'scarf', 'scarves'],
  ['scarves', 'scarf', 'scarves'],
  ['scenarios', 'scenario', 'scenarios'],
  ['schema', 'schema', 'schemata'],
  ['schemas', 'schema', 'schemas'],
  ['screen', 'screen', 'screens'],
  ['screens', 'screen', 'screens'],
  ['searches', 'search', 'searches'],
  ['securities', 'security', 'securities'],
  ['self', 'self', 'selves'],
  ['selves', 'self', 'selves'],
  ['sepsis', 'sepsi', 'sepses'],
  ['series', 'series', 'series'],
  ['serves', 'serve', 'serves'],
  ['services', 'service', 'services'],
  ['session', 'session', 'sessions'],
  ['sessions', 'session', 'sessions'],
  ['sheaf', 'sheaf', 'sheaves'],
  ['sheaves', 'sheaf', 'sheaves'],
  ['sheep', 'sheep', 'sheep'],
  ['shelf', 'shelf', 'shelves'],
  ['shelves', 'shelf', 'shelves'],
  ['shoes', 'shoe', 'shoes'],
  ['shoppingCarts', 'shoppingCart', 'shoppingCarts'],
  ['sieve', 'sieve', 'sieves'],
  ['sieves', 'sieve', 'sieves'],
  ['silex', 'silex', 'silices'],
  ['silices', 'silex', 'silices'],
  ['sketches', 'sketch', 'sketches'],
  ['sleeve', 'sleeve', 'sleeves'],
  ['sleeves', 'sleeve', 'sleeves'],
  ['slices', 'slice', 'slices'],
  ['smilies', 'smiley', 'smilies'],
  ['sofas', 'sofa', 'sofas'],
  ['software', 'software', 'software'],
  ['solves', 'solve', 'solves'],
  ['spans', 'span', 'spans'],
  ['species', 'species', 'species'],
  ['specimen', 'speciman', 'specimen'],
  ['specimens', 'specimen', 'specimens'],
  ['staff', 'staff', 'staff'],
  ['starves', 'starf', 'starves'],
  ['status', 'status', 'statuses'],
  ['statuses', 'status', 'statuses'],
  ['staves', 'stave', 'staves'],
  ['stigma', 'stigma', 'stigmata'],
  ['stimuli', 'stimulus', 'stimuli'],
  ['stockLevels', 'stockLevel', 'stockLevels'],
  ['stories', 'story', 'stories'],
  ['stratus', 'stratus', 'strati'],
  ['studies', 'study', 'studies'],
  ['studios', 'studio', 'studios'],
  ['study', 'study', 'studies'],
  ['stuff', 'stuff', 'stuffs'],
  ['subindices', 'subindex', 'subindices'],
  ['submatrices', 'submatrix', 'submatrices'],
  ['subscriptions', 'subscription', 'subscriptions'],
  ['suffix', 'suffix', 'suffixes'],
  ['summaries', 'summary', 'summaries'],
  ['survey', 'survey', 'surveys'],
  ['surveys', 'survey', 'surveys'],
  ['swerves', 'swerve', 'swerves'],
  ['synopsis', 'synopsis', 'synopses'],
  ['syntheses', 'synthesis', 'syntheses'],
  ['tag', 'tag', 'tags'],
  ['tags', 'tag', 'tags'],
  ['talkies', 'talkie', 'talkies'],
  ['tasks', 'task', 'tasks'],
  ['taxes', 'tax', 'taxes'],
  ['teams', 'team', 'teams'],
  ['teeth', 'tooth', 'teeth'],
  ['termini', 'terminus', 'termini'],
  ['territories', 'territory', 'territories'],
  ['themselves', 'themself', 'themselves'],
  ['theses', 'thesis', 'theses'],
  ['thesis', 'thesis', 'theses'],
  ['thief', 'thief', 'thieves'],
  ['thieves', 'thief', 'thieves'],
  ['threads', 'thread', 'threads'],
  ['tickets', 'ticket', 'tickets'],
  ['ties', 'tie', 'ties'],
  ['toes', 'toe', 'toes'],
  ['token', 'token', 'tokens'],
  ['tokens', 'token', 'tokens'],
  ['tomatoes', 'tomato', 'tomatoes'],
  ['tornado', 'tornado', 'tornadoes'],
  ['torpedo', 'torpedo', 'torpedoes'],
  ['townies', 'towny', 'townies'],
  ['twoFactorSecrets', 'twoFactorSecret', 'twoFactorSecrets'],
  ['uploads', 'upload', 'uploads'],
  ['user', 'user', 'users'],
  ['userProfile', 'userProfile', 'userProfiles'],
  ['userSessions', 'userSession', 'userSessions'],
  ['users', 'user', 'users'],
  ['uses', 'use', 'uses'],
  ['utilities', 'utility', 'utilities'],
  ['valley', 'valley', 'valleys'],
  ['valve', 'valve', 'valves'],
  ['valves', 'valve', 'valves'],
  ['verses', 'verse', 'verses'],
  ['vertex', 'vertex', 'vertices'],
  ['vertexes', 'vertex', 'vertexes'],
  ['vertices', 'vertex', 'vertices'],
  ['videos', 'video', 'videos'],
  ['villas', 'villa', 'villas'],
  ['virus', 'virus', 'viri'],
  ['viruses', 'virus', 'viruses'],
  ['volcano', 'volcano', 'volcanoes'],
  ['volcanoes', 'volcano', 'volcanoes'],
  ['wagon', 'wagon', 'wagons'],
  ['walkies', 'walky', 'walkies'],
  ['warehouses', 'warehouse', 'warehouses'],
  ['washes', 'wash', 'washes'],
  ['watches', 'watch', 'watches'],
  ['waves', 'wave', 'waves'],
  ['ways', 'way', 'ways'],
  ['webhooks', 'webhook', 'webhooks'],
  ['wishes', 'wish', 'wishes'],
  ['wives', 'wife', 'wives'],
  ['wolf', 'wolf', 'wolves'],
  ['wolves', 'wolf', 'wolves'],
  ['woman', 'woman', 'women'],
  ['women', 'woman', 'women'],
  ['workspaces', 'workspace', 'workspaces'],
  ['yes', 'yes', 'yeses'],
  ['zeros', 'zero', 'zeros'],
  ['zombies', 'zombie', 'zombies'],
] as const;

type Row = (typeof WORDS)[number];

/**
 * `'exact'` when the type names the same word `pluralize` does, `'loose'` when it declined to
 * decide — and an object, which fails the `extends string` below, when it named a different
 * word. The invariant/bivariant pair is what makes a union of candidates fail rather than
 * pass on one of its members.
 */
type Verdict<Actual extends string, Expected extends string> = string extends Actual
  ? 'loose'
  : [Actual] extends [Expected]
    ? [Expected] extends [Actual]
      ? 'exact'
      : { got: Actual; expected: Expected }
    : { got: Actual; expected: Expected };

/**
 * Distributes over the row union, so a single failing row names itself in the error rather
 * than collapsing the whole table into one unreadable message.
 */
type VerifySingular<R> = R extends readonly [infer W extends string, infer S extends string, string]
  ? Verdict<Singularize<W>, S>
  : never;
type VerifyPlural<R> = R extends readonly [infer W extends string, string, infer P extends string]
  ? Verdict<Pluralize<W>, P>
  : never;

/** Fails to instantiate — with the offending word in the message — if any row disagrees. */
type Verified<T extends string> = T;
type _SingularsMatch = Verified<VerifySingular<Row>>;
type _PluralsMatch = Verified<VerifyPlural<Row>>;

describe('type-level singular/plural', () => {
  it('records what pluralize actually returns for every word in the table', () => {
    const drifted = (WORDS as readonly Row[]).filter(
      ([word, singular, plural]) => pluralize.singular(word) !== singular || pluralize.plural(word) !== plural,
    );
    expect(drifted).toStrictEqual([]);
  });

  it('covers the shapes a table key actually takes', () => {
    const words = new Set<string>((WORDS as readonly Row[]).map(([word]) => word));
    // The two forms every schema has, and the pair the `ies` rules are easiest to get wrong on.
    for (const word of ['users', 'user', 'categories', 'category', 'cookies', 'movies', 'auditLogs']) {
      expect(words.has(word)).toBe(true);
    }
  });
});
